# Generated by Django 4.0.5 on 2022-06-30 18:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flia_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='cumple',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 30, 18, 54, 32, 296137, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familia',
            name='email',
            field=models.EmailField(default=datetime.datetime(2022, 6, 30, 18, 54, 37, 32100, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
    ]
